dist: trusty
sudo: required

language: python
python: 3.6

before_install:
  - sudo apt-get -qq update
  - travis_wait sudo apt-get install -y texlive-full
  - sudo apt-get install -y texlive-math-extra
  - sudo apt-get install -y texlive-xetex

install:
  - python -V
  - pip install jinja2

script:
  - python convert_json_to_tex.py
  - xelatex nnadeau-cv.tex

after_script:
  - find . -type f

notifications:
  email: false

deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: pq40AxXNMRkpOfiE5avjTyQkrIMV18Zm/50AaA3rN9sCBmXQ9R1i4qwzUKth1J1tEUGJwtROY9No3Dl9ffndIn3W/Fcs0U/cdSOCnYyko3gV6rqS7Zc8Vesai4bNCi4Qb1Pd3eacxU8rOzepljNspRVuPRjI1lyVC2BCLcuBA1uktHroVPioj+QzgnqZaBRXckjIKeghUwCNsxQAF1y9mGs+9cvKiQlE+Or1uJfeUiYb+/cfrePoav6sNcCGHyyQGr0AETHO5Shk0IP5A4tJLxniVSdMsWHeX/jvN6NzOEK/Nqq//ohzKBiECtTLOCeFodklaLrgMvZzh6PWr70EFAhjdaC9Y/FeDO23YscHpDN50J3Bix9FMfAIvuVc44YjiC8roL3It4KyZP3Z+obATf9Cf2N5sWPT9dOscDZs1xjKvjCqUfAjG9saJ51ebzDHk9KfJBq1b/g+G4Ib+aV8zn1SRqyjJE1FAN+HXMbzr7VC6FZsjfjWwlh/H6MvJvIWzfUsAh3rqhoMzmwGG2Ft3W4v2B7ofnQHNk3topXTttxIV7FPJGXvvzwKhBdZEqHo1CD6mbnJizBw2ixDPTKrwu+/48m6c/Ys3dgpH8aw7CmvOQm/C6NMtfTRZsd2di0aY7Vg4m8fuIdPHOomGK4vW9rF5h7Ozrvy+bQM+adPMZc=
    file: nnadeau-cv.pdf
    on:
      tags: true
      repo: nnadeau/cv
  - provider: pages
    skip_cleanup: true
    github_token:
      secure: pq40AxXNMRkpOfiE5avjTyQkrIMV18Zm/50AaA3rN9sCBmXQ9R1i4qwzUKth1J1tEUGJwtROY9No3Dl9ffndIn3W/Fcs0U/cdSOCnYyko3gV6rqS7Zc8Vesai4bNCi4Qb1Pd3eacxU8rOzepljNspRVuPRjI1lyVC2BCLcuBA1uktHroVPioj+QzgnqZaBRXckjIKeghUwCNsxQAF1y9mGs+9cvKiQlE+Or1uJfeUiYb+/cfrePoav6sNcCGHyyQGr0AETHO5Shk0IP5A4tJLxniVSdMsWHeX/jvN6NzOEK/Nqq//ohzKBiECtTLOCeFodklaLrgMvZzh6PWr70EFAhjdaC9Y/FeDO23YscHpDN50J3Bix9FMfAIvuVc44YjiC8roL3It4KyZP3Z+obATf9Cf2N5sWPT9dOscDZs1xjKvjCqUfAjG9saJ51ebzDHk9KfJBq1b/g+G4Ib+aV8zn1SRqyjJE1FAN+HXMbzr7VC6FZsjfjWwlh/H6MvJvIWzfUsAh3rqhoMzmwGG2Ft3W4v2B7ofnQHNk3topXTttxIV7FPJGXvvzwKhBdZEqHo1CD6mbnJizBw2ixDPTKrwu+/48m6c/Ys3dgpH8aw7CmvOQm/C6NMtfTRZsd2di0aY7Vg4m8fuIdPHOomGK4vW9rF5h7Ozrvy+bQM+adPMZc=
    on:
      repo: nnadeau/cv
