[personal]
first_name = "Nicholas"
last_name = "Nadeau"
titles = [
    "Professional Engineer (P.Eng.)", 
    "Associate Value Specialist (AVS)",
    ]
email = "nicholas.nadeau@gmail.com"
phone = "+1-514-573-5620"
website = "www.nicholasnadeau.me"
location = "Montréal, Canada"

[social_media.twitter]
name = "EngNadeau"
url = "https://twitter.com/EngNadeau"

[social_media.github]
name = "nnadeau"
url = "https://github.com/nnadeau/"

[[education]]
name = "PhD - Precision and Collaborative Robotics"
organization = "École de technologie supérieure"
location = "Montréal, Canada"
dates = [ "2014", "",]
summary = [ 
    "Thesis: Towards the Development of Safe, Collaborative Robotic Freehand Ultrasound", 
    "Created machine learning models and genetic algorithms for physical human-robot interaction.", 
    "Invented a novel, robust, low-cost robot calibration platform.",
    ]

[[education]]
name = "B.Eng. - Mechanical Engineering, Biomedical Engineering Minor"
organization = "McGill University"
location = "Montréal, Canada"
dates = [ "2010", "2014",]

[[education]]
name = "DEC - Honours Health Science"
organization = "Dawson College"
location = "Montréal, Canada"
dates = [ "2008", "2010",]

[[work]]
name = "Engineering Manager"
organization = "AON3D"
location = "Montréal, Canada"
dates = [ "2019", "",]
summary = [
    "Oversee and drive the design, development, testing, and deployment of innovative solutions for challenging problems in the additive manufacturing domain.", 
    "Ensure robust, scalable, reusable, efficient, production-quality software and hardware is being delivered to the organization.", 
    "Usher and evangelize adoption of engineering best-practices and methodology.", 
    "Set the roadmap, drive detailed planning, and ensure execution of deliverables for a medium sized team.", 
    "Mentor and help bringing up of new team members, help with interviewing and hiring of new team members, ensure technical development of team.", 
    "Research and incorporate emerging software infrastructures, tools, and technologies.",
    ]

[[work]]
name = "Senior R&D Engineer"
organization = "AON3D"
location = "Montréal, Canada"
dates = [ "2018", "2019",]
summary = [ 
    "Responsible for innovation and technology development to drive 10x revenue.", 
    "Introduced automated data collection framework to help drive business and engineering decisions.", 
    "Engineering ScrumMaster, responsible for ensuring the team has everything they need to deliver value.",
    ]

[[work]]
name = "R&D Engineer"
organization = "Rogue Research Inc."
location = "Montréal, Canada"
dates = [ "2011", "2018",]
summary = [ 
    "Responsible for mechanical research, design, and development of brain imaging and robotic products.", 
    "Developed trajectory generation algorithms (C++) for collaborative veterinary neurosurgery.", 
    "Created thermal models (Python) for transcranial magnetic stimulation coils.",
    ]

[[work]]
name = "Engineering & Technology Consultant"
organization = "YPC Technologies"
location = "Montréal, Canada"
dates = [ "2017", "2018",]
summary = [ 
    "Advised CEO throughout FounderFuel startup accelerator in order to go to market and raise seed capital.", 
    "Led a team of engineers and directed robotics and software design, development, and implementation.", 
    "Recommended long-term approach to strategic suppliers and technologies with the aim of optimizing operations and delivering savings.",
    ]

[[volunteer]]
name = "Reviewer"
organization = "Applied Mathematical Modelling"
location = ""
dates = [ "2019", "",]

[[volunteer]]
name = "Reviewer"
organization = "International Journal of Advanced Robotic Systems (IJARS)"
location = ""
dates = [ "2019", "",]

[[volunteer]]
name = "Reviewer"
organization = "The Journal of Open Source Software (JOSS)"
location = ""
dates = [ "2018", "",]

[[volunteer]]
name = "Communications Administrator"
organization = "Interaction du quartier Peter-McGill"
location = "Montréal, Canada"
dates = [ "2013", "2014",]

[[volunteer]]
name = "Discover McGill and Orientation Week Leader"
organization = "McGill University"
location = "Montréal, Canada"
dates = [ "2011", "2014",]

[[volunteer]]
name = "Treasurer and Communications Administrator"
organization = "Forum Jeunesse Centre-ville"
location = "Montréal, Canada"
dates = [ "2012", "2013",]

[[volunteer]]
name = "Volunteer Math and Science Teacher"
organization = "Innovation Jeunes"
location = "Montréal, Canada"
dates = [ "2009", "2011",]

[[awards]]
name = "Alexander Graham Bell Canada Graduate Scholarship"
organization = "NSERC"
date = "2015"

[[awards]]
name = "Mitacs Accelerate Industrial Research Grant"
organization = "Mitacs"
date = "2014"

[[awards]]
name = "Graduation Honours"
organization = "McGill University"
date = "2014"

[[awards]]
name = "Québec Iron Titanium Scholarship"
organization = "McGill University"
date = "2013"

[[awards]]
name = "Abe and Jennie Brock Award"
organization = "McGill University"
date = "2013"

[[awards]]
name = "Dean's Honour List"
organization = "McGill University"
date = "2013"

[[awards]]
name = "Industrial Undergraduate Research Award"
organization = "NSERC"
date = "2013"

[[awards]]
name = "Industrial Undergraduate Research Award"
organization = "NSERC"
date = "2012"

[[awards]]
name = "Industrial Undergraduate Research Award"
organization = "NSERC"
date = "2011"

[[awards]]
name = "Golden Key International Honour Society"
organization = "McGill University"
date = "2011"
is_exclude = true

[[awards]]
name = "First Class Graduation Honours"
organization = "Dawson College"
date = "2010"
is_exclude = true

[[awards]]
name = "Athletic Academic Achievement Award"
organization = "Dawson College"
date = "2010"
is_exclude = true

[[languages]]
name = "English"
fluency = "Native"

[[languages]]
name = "French"
fluency = "Native"

[[certifications]]
name = "Professional Engineer (P.Eng.)"
organization = "Ordre des ingénieurs du Québec (OIQ)"

[[certifications]]
name = "Associate Value Specialist (AVS)"
organization = "SAVE International"

[[certifications]]
name = "Open Water Diver"
organization = "Professional Association of Diving Instructors (PADI)"

[[talks]]
name = "Speaker - Evolutionary Motion Control Optimization in Physical Human-Robot Interaction"
organization = "2018 IEEE/RSJ International Conference on Intelligent Robots and Systems (IROS)"
date = "2018-10"

[[talks]]
name = "Speaker - Calibrating Robots with Python"
organization = "PyCon Canada 2017"
date = "2017-11"

[[talks]]
name = "Speaker - Calibrating Robots with Python"
organization = "Montréal-Python 67"
date = "2017-10"

[[talks]]
name = "Keynote - Robotics and Neuroscience"
organization = "Clearpoint Elementary Exhibition Summit"
date = "2016-12"

[[talks]]
name = "Speaker - Medical Robotics"
organization = "McGill Faculty of Medicine Explore Camp"
date = "2015-06"

[[talks]]
name = "Keynote"
organization = "Riverdale High School Career Seminar"
date = "2014-05"

[[talks]]
name = "Keynote"
organization = "Riverdale High School Career Seminar"
date = "2014-02"

[[talks]]
name = "Keynote"
organization = "Lester B. Pearson School Board Science Showcase"
date = "2013-05"

[[workshops]]
name = "MUSE 1.0 Bedside Ultrasound Course for Primary Care Clinicians"
organization = "McGill University Steinberg Centre for Simulation and Interactive Learning"
location = "Montréal, Canada"
date = "2017-01"

[[workshops]]
name = "Collaborative Robots Workshop"
organization = "RIA International"
location = "Boston, U.S."
date = "2016-05"

[[projects]]
name = "Team Coordinator and Electronics Designer - Formula SAE"
organization = "McGill Racing Team"
location = "Montréal, Canada"
dates = [ "2010", "2013",]

[[projects]]
name = "Mechanical Designer - Electricity-free Polymerase Chain Reaction (PCR) System"
organization = "McGill University Micro and NanoBioengineering Lab"
location = "Montréal, Canada"
dates = [ "2013", "2014",]

[[publications]]
name = "Impedance Control Self-Calibration of a Collaborative Robot Using Kinematic Coupling "
authors = "Nicholas A. Nadeau, Ilian A. Bonev"
organization = "Robotics"
date = "2019"

[[publications]]
name = "Evolutionary Motion Control Optimization in Physical Human-Robot Interaction"
authors = "Nicholas A. Nadeau, Ilian A. Bonev"
organization = "IEEE/RSJ International Conference on Intelligent Robots and Systems (IROS)"
date = "2018"

[[publications]]
name = "An Extrinsic Dexterity Approach to the IROS 2018 Fan Robotic Challenge Modality B"
authors = "Jennifer Kwiatkowski, Jean-Philippe Roberge, Nicholas A. Nadeau, Louis L'Écuyer-Lapierre, Vincent Duchaine"
organization = "IEEE/RSJ International Conference on Intelligent Robots and Systems (IROS)"
date = "2018"

[[publications]]
name = "Characterization of a robotic micro-surgical system for small-animal neurosurgery"
authors = "Nicholas A. Nadeau, Alexandru Ciobanu, Fred Lamer, Mathieu Coursolle, Sean McBride, Stephen Frey, Roch Comeau"
organization = "Society for Neuroscience"
date = "2017"
