name: Build

on:
  pull_request:
    branches:
      - master
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build PDF
        run: make pdf
      - name: Archive PDF
        uses: actions/upload-artifact@v3
        with:
          name: pdf
          path: out/*.pdf
          retention-days: 5
